repository:
  name: gemini-repl
  description: Simple REPL interface for Gemini API in ClojureScript with formal specifications
  topics:
    - clojurescript
    - gemini-api
    - repl
    - formal-methods
    - tla-plus
    - alloy
    - literate-programming
    - shadow-cljs
  private: false
  has_issues: true
  has_projects: false
  has_wiki: false
  has_downloads: true
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  delete_branch_on_merge: true
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true

labels:
  - name: bug
    color: d73a4a
    description: Something isn't working
  - name: enhancement
    color: a2eeef
    description: New feature or request
  - name: documentation
    color: 0075ca
    description: Improvements or additions to documentation
  - name: rfc
    color: 7057ff
    description: Request for Comments
  - name: formal-methods
    color: 008672
    description: Related to TLA+ or Alloy specifications
  - name: validation
    color: d876e3
    description: Related to formal validation
  - name: tooling
    color: ffd300
    description: Development tooling and infrastructure
